name: Build and Release

on:
  push:
    tags:
      - '*'


env:
  EXECUTABLE_NAME: syncback-lfs


jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        os: [windows, macos, linux]
        include:
          - os: windows
            goos: windows
            goarch: amd64
            extension: .exe
          - os: macos
            goos: darwin
            goarch: amd64
            extension: ""
          - os: macos
            goos: darwin
            goarch: arm64
            extension: ""
          - os: linux
            goos: linux
            goarch: amd64
            extension: ""

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version: '^1.22'

    - name: Set output file name
      run: |
        echo "EXECUTABLE_FILE=${{ env.EXECUTABLE_NAME }}${{ matrix.extension }}" >> $GITHUB_ENV
        echo "OUTPUT_FILE=output/${{ matrix.goos }}-${{ matrix.goarch }}/$EXECUTABLE_FILE" >> $GITHUB_ENV

    - name: Go build
      env:
        GOOS: ${{ matrix.goos }}
        GOARCH: ${{ matrix.goarch }}
      run: |
        go version

        go build -o ${{ env.EXECUTABLE_FILE }} cmd/main.go
        echo "Built ${{ env.EXECUTABLE_FILE }}"

    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: ${{ matrix.goos }}-${{ matrix.goarch }}
        path: ${{ env.EXECUTABLE_FILE }}

  release:
    if: startsWith(github.ref, 'refs/tags/')
    needs: build
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Download artifact
      uses: actions/download-artifact@v4
      with:
        path: ./releases

    - name: test
      run: |
        ls -R ./releases

    - name: Find and update release with artifacts
      uses: softprops/action-gh-release@v2
      with:
        files: ./releases/*
